### ISSUE TITLE
QR Code too big to fit in the screen. 

### ISSUE THREAD

**Issue by adarshsrivastava11** [Baozisoftware/qrcode-terminal-go#1]
Hi, whenever I'm running the examples, the QR code that I'm getting is too large to fit in the screen and thus can't be scanned. I'd be grateful if you could tell me a way to downsize them.

![screen shot 2019-02-23 at 3 32 10 am](https://user-images.githubusercontent.com/14872767/53273954-93832180-371b-11e9-8790-c2e6bbe33096.png)
![screen shot 2019-02-23 at 3 32 18 am](https://user-images.githubusercontent.com/14872767/53273958-954ce500-371b-11e9-92cf-6eea8debcf39.png)

System Mac OS, Terminal - iTerm, upterm, default terminal. Shells - Bash, ZSH

**Comment by Baozisoftware** [comment]
Sorry, you can only change the window size at present, because it is output according to the bitmap, unless there is a way to compress it?

**Comment by hajsf** [comment]
Any update on this?
